version = 1
SPDX-PackageName = "NGV-FBMC"
SPDX-PackageSupplier = "Open Energy Transition gGmbH <tyndp@openenergytransition.org>"
SPDX-PackageDownloadLocation = "https://github.com/open-energy-transition/NGV-FBMC"

[[annotations]]
path = [
    "data/NGV-FBMC/primary/20260326/**",
]
SPDX-FileCopyrightText = [
    "2026 N-SIDE"
]
SPDX-License-Identifier = "LicenseRef-AllRightsReserved"

[[annotations]]
path = [
    "pixi.lock",
]
SPDX-FileCopyrightText = [
    "NGV-FBMC contributors"
]
SPDX-License-Identifier = "MIT"