# SPDX-FileCopyrightText: NGV-FBMC contributors
#
# SPDX-License-Identifier: MIT

# Contains additional configuration options that overwrite the defaults
# coming from the gb-dispatch-model.

renewable:
  "offwind-dc":
    correction_factor: 0.70840 # 80% of default 0.8855 to align with reported FES2024 load factors

dukes-fuel-prices:
  sheet-config:
    skiprows: 15 # Fix - currently necessary as data contains an unexpected comment row.
