run:
  prefix: ""
  name: "ngv-fbmc"

# Conversion rate for GBP to EUR
# Choosen consistently with the GB dispatch model
# average in 2021: https://www.exchangerates.org.uk/GBP-EUR-spot-exchange-rates-history-2021.html#:~:text=This%20is%20the%20British%20Pound,rate%20in%202021%3A%201.1632%20EUR.
GBP_to_EUR: 1.1632

# Max and min annual capacity factors for the nuclear generators across the model
conventional:
  nuclear:
    max_annual_capacity_factor: 1
    min_annual_capacity_factor: 0.50

sector:
  co2_sequestration_potential:
    # Values from TYNDP 2024 Supply Tool
    2030: 47
    2040: 344

electricity:
  renewable_carriers: []
  tyndp_renewable_carriers:
    - other-res
    - hydro-ror
    - hydro-reservoir
    - hydro-pondage
    - hydro-phs
    - hydro-phs-pure
    - onwind
    - solar-pv-utility
    - solar-pv-rooftop
    - offwind-ac-fb-r
    - offwind-ac-fl-r
    - offwind-dc-fb-r
    - offwind-dc-fl-r
    - offwind-dc-fb-oh
    - offwind-dc-fl-oh
    - offwind-h2-fb-oh
    - offwind-h2-fl-oh

carrier_mapping:
  Generator:
    Load Shedding: load
    biomass: solid biomass
    engine: oil-heavy
    geothermal: geothermal
    nuclear: nuclear
    offwind-dc: offwind-dc-fl-oh
    oil: oil-heavy
    solar: solar-pv-utility
    waste: waste
    CCGT: gas-ccgt
    OCGT: OCGT
  Link:
    Baseline Electricity (I&C) DSR reverse: battery discharger
    Baseline Electricity (I&C) DSR shift: battery charger
    Baseline Electricity (Residential) DSR reverse: battery discharger
    Baseline Electricity (Residential) DSR shift: battery charger
    Baseline Electricity unmanaged load: electricity distribution grid
    EV DSR reverse: home battery discharger
    EV DSR shift: home battery charger
    EV unmanaged load: home battery charger
    H2 Turbine: h2-ccgt
    I&C Heat DSR reverse: battery discharger
    I&C Heat DSR shift: battery charger
    I&C Heat unmanaged load: electricity distribution grid
    Residential Heat DSR reverse: battery discharger
    Residential Heat DSR shift: battery charger
    Residential Heat unmanaged load: electricity distribution grid
    EV V2G: home battery discharger
  Load:
    AC: electricity
    Baseline Electricity: electricity
    EV: electricity
    H2: H2 exogenous demand
    I&C Heat: electricity
    Residential Heat: electricity
  StorageUnit:
    Battery Storage: battery
    PHS: hydro-phs
    hydro: hydro-reservoir
  Store:
    Baseline Electricity (I&C) DSR: battery
    Baseline Electricity (Residential) DSR: battery
    EV DSR: home battery
    I&C Heat DSR: battery
    Residential Heat DSR: battery
    EV V2G: home battery

time_aggregation:
  enable: true
  method: segment
  parameters:
    num_segments: 2190 # 4x smaller snapshots size
    exclude_attrs: ["e_min_pu", "e_max_pu"] # Concern from GB model: demand-side flexibility implemented via store. Concern: Step changes could confuse the segmentation algorithm

solving:
  options:
    load_shedding: 4e3
    noisy_costs: false # Upstream models already run solve_network once, so no need to add noise here again
    include_objective_constant: false
  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    threads: 8
    gurobi-default:
      BarConvTol: 1.e-6
    cplex-default:
      barrier.convergetol: 1.e-6

explicit_allocation:
  # All connections to and from buses that start with e.g. "GB"
  to_from: "GB"
  # Carriers for the links; note, only Link components are supported, not Line components
  connection_types:
    - DC
  # List of all the connections for which the explicit allocation should be applied
  # Connections may reference to one or more connection, by using regex wildcards for the name.
  # E.g. "GBOH001-DKWOH01-Offshore DC-20[34]0" will apply to
  # "GBOH001-DKWOH01-Offshore DC-2030" and "GBOH001-DKWOH01-Offshore DC-2040"
  connections:
    - Aminth
    - BritNed
    - Cronos
    - ElecLink
    - FAB Link
    - Gridlink
    - IFA\d? # Matches IFA and IFA2
    - Kulizumboo
      # - LionLink \(EuroLink\) # Not build in newer versions
    - NS Link \(NSL\)
    - Nautilus
    - Nemo
    - NeuConnect
    - SENECA
      # - Tarchon # Not build in newer versions
    - Viking Link
      # Connected to IE/NI - optimal allocation
      # - East-West
      # - Gallant
      # - Greenlink (Greenwire)
      # - LirIC
      # - MARES
      # - Moyle
      # Connected to Norway - optimal allocation
      # - Continental Link
      # - NorthConnect

forecast_errors:
  component_carrier_mapping:
    # Mapping of the technology names used in the forecast error file to the component and carrier names in the network file
    # Note: The names of the carriers will be matched as "carriers containing this string independent of case", so e.g.
    # "offwind" will match "Offwind", "offwind-dc", etc.
    "_Wind":
      - "|generators|onwind"
      - "|generators|offwind"
    "_Solar":
      - "|generators|solar-pv"
    "_Load":
      - "|loads|electricity"
  bus_mapping:
    # Mapping of the bus names in the forecast error file to the bus names in the network file
    # Note: These names are matched as "strings starting with...", so e.g. "GB 1" also matches "GB 10", "GB 11", etc.
    # which is why these must NOT be repeated, else the same forecast errors will be applied to these buses multiple times
    # TODO check again with the merged model, might require some adjustments
    "AT":
      - "AT00"
    "BE":
      - "BE00"
      - "BEIOH01"
      - "BEOH001"
    "CH":
      - "CH00"
    "CZ":
      - "CZ00"
    "DE":
      - "DE00"
      - "DEOH001"
      - "DEOH002"
      - "DEOR001"
    "DK1":
      - "DKE1"
      - "DKE0R01"
    "DK2":
      - "DKW1"
      - "DKW0R01"
    "ES":
      - "ES00"
      - "ESOH001"
      - "ESOH003"
      - "ESOH002"
    "FI":
      - "FI00"
      - "FIOH001"
    "FR":
      - "FR00"
      - "FR15"
      - "FROH001"
      - "FROH002"
      - "FROH003"
    "GB":
      - "GB 1" # also matches "GB 10", "GB 11", etc.
      - "GB 2" # also matches "GB 20", "GB 21", etc.
      - "GB 3" # also matches "GB 31"
      - "GB 4"
      - "GB 5"
      - "GB 6"
      - "GB 7"
      - "GB 8"
      - "GB 9"
    "HR":
      - "HR00"
      - "HROH001"
    "IE":
      - "IE00"
      - "IEOH001"
    "ITCA":
      - "ITCA"
    "ITCN":
      - "ITCN"
      - "ITCNOR1"
    "ITCS":
      - "ITCS"
      - "ITCSOR1"
    "ITN1":
      - "ITN1"
      - "ITN1OR1"
    "ITS1":
      - "ITS1"
      - "ITS1OR1"
    "ITSA":
      - "ITSA"
      - "ITSAOR1"
    "ITSI":
      - "ITSI"
      - "ITSIOR1"
    "NL":
      - "NL00"
      - "NLOR001"
      - "NLOH001"
    "NO1":
      - "NOS0"
      - "NOSOH01"
      - "NOSOH02"
      - "NOSOR01"
    "NO3":
      - "NOM1"
      - "NOMOH01"
    "NO4":
      - "NON1"
      - "NONOH01"
    "PL":
      - "PL00"
      - "PLOH001"
    "PT":
      - "PT00"
      - "PTOH001"
    "SE1":
      - "SE01"
      - "SEOR001"
    "SE2":
      - "SE02"
      - "SEOH001"
    "SE3":
      - "SE03"
      - "SEOH002"
    "SE4":
      - "SE04"
      - "SEOH003"
    # not part of the TYNDP
    # "NO2":
    # missing forecast errors
    # "AL":
    # "BA":
    # "BG":
    # "EE":
    # "GR":
    # "HU":
    # "ITVI":
    # "LT":
    # "LU":
    # "LV":
    # "ME":
    # "MK":
    # "MT":
    # "RO":
    # "RS":
    # "SI":
    # "SK":
