# SPDX-FileCopyrightText: NGV-FBMC contributors
#
# SPDX-License-Identifier: MIT

# Contains additional configuration options that overwrite the defaults
# coming from the NGV-IEM model

# Need an entry such that Snakemake considers this a valid yaml file
# Can be removed once there are other actual entries in this file
place: holder
